### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by ohlincik** [rkingon/Craft-Plugin--Sprockets#1]
Hi Roi,

I followed the documentation diligently but for some reason no matter what I do, I always get the same error:

```
exception type Sprockets\Exception\FileNotFound (The asset file 'application' of type 'css' wasn't found.
```

At first I had the 'application.css' file inside the 'stylesheets' directory as is specified in the docs. Then I tried to move it to the 'assets' directory. Did not help. Any insight would be appreciated.

Thanks!

**Comment by rkingon** [comment]
What does your project's folder tree look like? application.css goes within stylesheets, so revert to that

**Comment by rkingon** [comment]
Also- verify you have standard file permissions on application (chmod 644 application.css)
